// 定义 Memory 文件, 注入和整合流程共同使用的固定预算.

export const MEMORY_SUMMARY_TOKENS = 2_500;
export const MEMORY_CONSOLIDATION_ITEMS = 256;
export const MEMORY_CONSOLIDATION_INPUT_BYTES = 16 * 1024 * 1024;
export const MEMORY_GIT_DIFF_BYTES = 16 * 1024 * 1024;
export const MEMORY_EXTRACTION_CONCURRENCY = 2;
export const MEMORY_CONSOLIDATION_MIN_RESULTS = 8;
export const MEMORY_CONSOLIDATION_MAX_WAIT_MS = 6 * 60 * 60 * 1000;
export const MEMORY_CONSOLIDATION_CHECK_INTERVAL_MS = 60 * 60 * 1000;
export const MEMORY_MAINTENANCE_INTERVAL_MS = 12 * 60 * 60 * 1000;
export const MEMORY_RELATIONSHIP_HISTORY_ACTIVE_DAYS = 180;
export const MEMORY_STORAGE_MAX_BYTES = 1024 * 1024 * 1024;
export const MEMORY_STORAGE_WARNING_BYTES = Math.floor(MEMORY_STORAGE_MAX_BYTES * 0.8);
