/**
 * EmaAgent Constants Core — 集中式运行时常量。
 *
 * 所有跨包共用的硬编码值（阈值、超时、限额、枚举全集）集中于此。
 * 原则：严禁在业务代码中裸写魔法数字/字符串，一律引用此包的常量。
 *
 * ```
 * import {
 *   REPEATED_ERROR_LIMIT,
 *   DEFAULT_REACT_MAX_STEPS,
 *   SHELL_TIMEOUT_MS,
 *   MODEL_ROLES,
 *   HTTP_STATUS,
 *   ...
 * } from "@ema-agent/constants-core"
 * ```
 */

// ---- Agent / ReAct ----
export {
  REPEATED_ERROR_LIMIT,
  DEFAULT_REACT_MAX_STEPS,
  MAX_PARALLEL_READONLY_TOOLS,
  AGENT_RISK_LEVELS,
  REACT_STATUSES,
  REACT_STEP_TYPES,
  READ_ONLY_TOOL_PATTERNS,
  DANGEROUS_TOOL_NAMES,
  DANGEROUS_FILE_OPERATIONS,
  BUILTIN_TOOL_NAMES,
} from "./agent.js"

// ---- Model / Provider ----
export {
  PROVIDER_CATEGORIES,
  PROVIDER_KINDS,
  PROVIDER_HEALTH_STATUSES,
  PROVIDER_PRIORITY,
  MODEL_ROLES,
  CHAT_MESSAGE_ROLES,
  DEFAULT_CONTEXT_WINDOWS,
  DEFAULT_MAX_OUTPUT_TOKENS,
  FALLBACK_CONTEXT_WINDOW,
  FALLBACK_MAX_OUTPUT_TOKENS,
  DEFAULT_MODEL_IDS,
  DEFAULT_PRICING,
} from "./model.js"

// ---- Multimodal ----
export {
  AUDIO_CODECS,
  AUDIO_SAMPLE_RATES,
  AUDIO_CHANNELS,
  TTS_RESPONSE_FORMATS,
  VOICE_EMOTIONS,
  IMAGE_GEN_STYLES,
  IMAGE_GEN_SIZES,
  IMAGE_GEN_QUALITIES,
  IMAGE_GEN_DEFAULTS,
  EMOTION_LABELS,
  MODERATION_CATEGORIES,
  LIVE2D_EXPRESSIONS,
  LIVE2D_MOTIONS,
  LIVE2D_MOUTH_MODES,
  BREATH_LEVELS,
  PHONEME_SYMBOLS,
  PHONEME_DURATION_MS,
  PAUSE_DURATION_MS,
} from "./multimodal.js"

// ---- Limits ----
export {
  SHELL_TIMEOUT_MS,
  PYTHON_TIMEOUT_MS,
  HTTP_REQUEST_TIMEOUT_MS,
  STT_SILENCE_TIMEOUT_MS,
  TURN_LOCK_TIMEOUT_MS,
  PROVIDER_HEALTH_CHECK_TIMEOUT_MS,
  COMMAND_MAX_OUTPUT_BYTES,
  FILE_READ_MAX_BYTES,
  MAX_SEARCH_FILES,
  ERROR_TEXT_TRUNCATE,
  ERROR_RAW_TRUNCATE,
  ATTACHMENT_MAX_BYTES,
  DEFAULT_CONTEXT_BUDGET,
  OUTPUT_TOKEN_RESERVE_RATIO,
  OUTPUT_TOKEN_RESERVE_CAP,
  CHARS_PER_TOKEN_ESTIMATE,
  RECENT_MESSAGES_PAGE_SIZE,
  SESSION_LIST_PAGE_SIZE,
  MEMORY_RECALL_LIMIT,
  SESSION_TITLE_MAX_LENGTH,
  TITLE_TRUNCATION_SUFFIX,
  LOCAL_DEV_CHUNK_SIZE,
  LOCAL_DEV_CHUNK_DELAY_MS,
  LOCAL_DEV_TITLE_TRUNCATE,
  DEFAULT_FACT_CONFIDENCE,
  ROLLING_SUMMARY_PRIORITY,
  USER_PROFILE_PRIORITY,
  RECENT_MESSAGES_PRIORITY,
} from "./limits.js"

// ---- HTTP ----
export {
  HTTP_STATUS,
  RETRYABLE_HTTP_STATUSES,
  isRetryableStatus,
  API_VERSIONS,
  AUTH_ERROR_PATTERNS,
  RATE_LIMIT_ERROR_PATTERNS,
  MODEL_ERROR_PATTERNS,
  BFF_PORT,
  PYTHON_BRIDGE_PORT,
  EDGE_TTS_PORT,
} from "./http.js"

// ---- Paths ----
export {
  WORKSPACE_TMP_DIR,
  DEFAULT_PYTHON_COMMAND,
  SKIP_DIRECTORIES,
  BINARY_FILE_EXTENSIONS,
  isBinaryFile,
} from "./paths.js"
