import type {
  SessionId,
  TurnId,
  TurnMode,
  AgentSubMode,
  ArtifactId,
  CharacterCardId,
} from './ids.js';
import type { LlmProtocol } from './providers/types.js';
import type { UsageSummary } from './turns.js';

// ── Shared sub-types ──────────────────────────────────────────────────────────

export type { UsageSummary };

export interface ToolError {
  code: string;
  message: string;
}

export interface Artifact {
  id: ArtifactId;
  type: string;
  title: string;
  content: string | null;
  contentLocation: 'inline' | 'file';
  contentPath?: string;
  meta: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
  appliedAt?: number;
  rejectedAt?: number;
}

export interface StageCue {
  motion?: string;
  expression?: string;
  lipsync?: LipSyncFrame[];
  durationMs?: number;
  priority: number;
}

export interface LipSyncFrame {
  t: number;
  mouth: number;
}

export interface EmotionState {
  primary: string;
  secondary?: string;
  intensity: number;
}

/**
 * One question inside an `ask_user_required` batch. Mirrors the shape the
 * built-in `ask_user` tool accepts as input, with an added stable `id` so the
 * orchestrator can correlate answers back to the question.
 */
export interface AskUserQuestionSpec {
  /** Stable per-batch question id (e.g. `q0`, `q1`). Used as the key in `answers`. */
  id: string;
  /** The question shown to the user. */
  question: string;
  /** Very short label (≤12 chars) shown as a chip/tag in the UI. */
  header: string;
  /**
   * Multiple-choice options. Omit for freeform text answer.
   * When present, `multiSelect` decides whether the UI allows multiple picks.
   */
  options?: Array<{ label: string; description?: string }>;
  multiSelect?: boolean;
  /** When true, the UI shows an "Other (custom)" free-text fallback alongside options. */
  allowCustom?: boolean;
  /** Placeholder shown in the text input (text questions only). */
  placeholder?: string;
}

// ── EmaStreamEvent union ──────────────────────────────────────────────────────

export type EmaStreamEvent =
  // Turn lifecycle
  | { type: 'turn_started'; turnId: TurnId; mode: TurnMode; subMode?: AgentSubMode }
  | { type: 'turn_completed'; turnId: TurnId; usage: UsageSummary }
  | { type: 'turn_failed'; turnId: TurnId; code: string; message: string }
  | { type: 'turn_aborted'; turnId: TurnId; reason: string }

  // Text streaming — blockIndex tracks position within the assistant's block array
  | { type: 'output_text_delta';    blockIndex: number; delta: string }
  | { type: 'output_text_complete'; blockIndex: number; text: string }

  // Reasoning / thinking blocks (DeepSeek-R1, Claude extended thinking)
  | { type: 'reasoning_delta';    blockIndex: number; delta: string }
  | { type: 'reasoning_complete'; blockIndex: number }

  // Tool calls — blockIndex lets the frontend know where in the block list this tool sits
  | { type: 'tool_call_partial';  blockIndex: number; callId: string; name: string; argsDelta: string }
  | { type: 'tool_call_complete'; blockIndex: number; callId: string; name: string; args: unknown }
  | { type: 'tool_result';        callId: string; output?: unknown; error?: ToolError }

  // Permission
  // `humanDescription` is an optional plain-language explanation of what the
  // tool will do, generated by the tool-explainer LLM (V1.5). Frontend shows
  // it above the raw command so non-technical users can decide.
  | {
      type: 'permission_required';
      promptId: string;
      tool: string;
      args: unknown;
      hint: string;
      humanDescription?: string;
    }
  | { type: 'permission_resolved'; promptId: string; decision: 'allow' | 'deny' }

  // Ask-user — emitted by the built-in `ask_user` tool when it runs under a
  // streaming context (Tauri / SSE). One event carries the full question
  // batch (1-4 questions); the orchestrator awaits the matching POST
  // /api/permission/:promptId/respond before the tool resolves.
  | {
      type: 'ask_user_required';
      promptId: string;
      questions: AskUserQuestionSpec[];
      humanDescription?: string;
    }
  | {
      type: 'ask_user_resolved';
      promptId: string;
      /** Keyed by question.id; the value is the user's free-text or joined option labels. */
      answers: Record<string, string>;
    }

  // Artifact
  | { type: 'artifact_upserted'; artifact: Artifact }
  | { type: 'artifact_applied'; id: ArtifactId }

  // Stage / Emotion
  // turnId lets the frontend ignore cues from a preempted turn (concurrent sends).
  | { type: 'stage_cue'; turnId: TurnId; cue: StageCue }
  | { type: 'emotion_changed'; turnId: TurnId; state: EmotionState }

  // TTS — audio is base64-encoded string over SSE
  | { type: 'tts_chunk'; audio: string; lipsync?: LipSyncFrame[]; sentenceId: string }
  | { type: 'tts_sentence_complete'; sentenceId: string }

  // Narrative
  | { type: 'narrative_route_resolved'; timelines: string[] }
  | { type: 'narrative_timeline_complete'; timeline: string; charCount: number; snippet: string }

  // Memory — turn-scoped (emitted via beforeLlm hook + compaction)
  | { type: 'context_compacted'; before: number; after: number; method: string }
  | { type: 'recall_evidence'; sources: string[]; itemCount: number }

  // Memory — pipeline observability (cross-turn, emitted on the system bus)
  | { type: 'memory_extraction_started';    sessionId: SessionId; turnId?: TurnId; queueDepth: number }
  | { type: 'memory_extraction_completed';
      sessionId: SessionId; nodes: number; edges: number; items: number;
      lazyQueued: number; durationMs: number }
  | { type: 'memory_extraction_failed';     sessionId: SessionId; error: string }
  | { type: 'memory_consolidation_started'; nodeCount: number }
  | { type: 'memory_consolidation_completed'; consolidated: number; durationMs: number }
  | { type: 'memory_maintenance_completed'; decayedNodes: number; decayedItems: number; dryRun: boolean; durationMs: number }
  | { type: 'memory_node_merged';           nodeId: string; label: string; fragmentCount: number }
  | { type: 'memory_index_rebuilt';         backend: string; nodes: number; items: number; durationMs: number }

  // Background tasks — system-scoped (memory queue worker telemetry)
  | { type: 'background_task_started';   taskId: string; kind: string; sessionId?: SessionId }
  | { type: 'background_task_completed'; taskId: string; kind: string; durationMs: number }
  | { type: 'background_task_failed';    taskId: string; kind: string; error: string }

  // Agent
  | { type: 'agent_iteration'; n: number }
  | { type: 'agent_breaker_tripped'; reason: string }

  // Sub-agent (V1.5 — events reserved now so the frontend bubble system can
  // plug in without a contracts migration later). The runtime that spawns
  // sub-agents is not implemented in V1; the subagent tool stays a stub.
  | { type: 'subagent_started';   subagentId: string; parentTurnId: TurnId; description?: string; promptExcerpt: string }
  | { type: 'subagent_progress';  subagentId: string; iteration: number; lastTool?: string }
  | { type: 'subagent_completed'; subagentId: string; outputExcerpt: string; usage: UsageSummary; durationMs: number }
  | { type: 'subagent_failed';    subagentId: string; error: string }
  | { type: 'subagent_aborted';   subagentId: string; reason: string }

  // Provider health
  | {
      type: 'provider_health_changed';
      provider: LlmProtocol;
      status: 'ok' | 'failed' | 'probing' | 'unknown';
      latencyMs?: number;
      error?: string;
    }

  // Character card
  | { type: 'character_card_switched'; cardId: CharacterCardId; name: string }

  // System
  | { type: 'system_warning'; level: 'info' | 'warn' | 'error'; message: string }

  // NOTE: heartbeat is NOT pushed through TurnEventStore.
  // It is sent as a raw `event: heartbeat\ndata: {}\n\n` SSE frame directly
  // by the GET /events handler's setInterval via encodePing(). This keeps
  // keep-alive frames out of the replay buffer. The frontend must listen on
  // the `heartbeat` SSE event name (addEventListener('heartbeat', ...)), not
  // parse this as a JSON EmaStreamEvent.
  | { type: 'heartbeat'; ts: number };
