-- Provider 种子：19 个内置供应商的能力、协议档与离线建议模型。
-- 全部 INSERT OR IGNORE；providers 无启停列，能力可用性 = active_protocol + key。
-- created_at 1..19 即设置页卡片顺序（providers 列表按 created_at ASC 排序）。
-- 演进规则（写进施工单）：后续新增 provider/协议/建议模型只追加新迁移；
-- 协议与模型演进必须 WHERE EXISTS 对应 providers / provider_capabilities 行，
-- 尊重用户删除；永不 UPDATE/DELETE 用户行。
-- embed dim 按公开规格填写；待核：jina-embeddings-v2-base-zh(768)、
-- zhipu embedding-3(2048)、togethercomputer/m2-bert-80M-8k-retrieval(768)、
-- ollama vision 上下文窗口 llava(4096)/llava-llama3(8192)/moondream(2048)。
-- vision 静态清单只保留 models.dev 未收录的（ollama 本地）；
-- openai/siliconflow 等 modelsDevId 已收录的 vision 建议一律不种子，避免双份事实。
-- lmstudio embed 的 'auto' 是占位符不是真模型，不种子（live 拉取覆盖）。

INSERT OR IGNORE INTO providers (id, name, icon_id, auth_type, created_at, updated_at) VALUES
  ('openai',      'OpenAI',               'openai',      'bearer',  1,  1),
  ('anthropic',   'Anthropic',            'anthropic',   'bearer',  2,  2),
  ('gemini',      'Google Gemini',        'gemini',      'bearer',  3,  3),
  ('deepseek',    'DeepSeek',             'deepseek',    'bearer',  4,  4),
  ('moonshot',    'Moonshot Kimi',        'moonshot',    'bearer',  5,  5),
  ('zhipu',       '智谱 GLM',             'zhipu',       'bearer',  6,  6),
  ('openrouter',  'OpenRouter',           'openrouter',  'bearer',  7,  7),
  ('groq',        'Groq',                 'groq',        'bearer',  8,  8),
  ('mistral',     'Mistral',              'mistral',     'bearer',  9,  9),
  ('xai',         'xAI Grok',             'xai',         'bearer', 10, 10),
  ('perplexity',  'Perplexity',           'perplexity',  'bearer', 11, 11),
  ('together',    'Together AI',          'together',    'bearer', 12, 12),
  ('fireworks',   'Fireworks AI',         'fireworks',   'bearer', 13, 13),
  ('ollama',      'Ollama',               'ollama',      'none',   14, 14),
  ('lmstudio',    'LM Studio',            'lmstudio',    'none',   15, 15),
  ('siliconflow', 'SiliconFlow',          'siliconflow', 'bearer', 16, 16),
  ('jina',        'Jina AI',              'jina',        'bearer', 17, 17),
  ('dashscope',   '阿里云百炼 (DashScope)', 'dashscope', 'bearer',  18, 18),
  ('gpt-sovits',  'GPT-SoVITS (本地)',    'gpt-sovits',  'none',   19, 19);

INSERT OR IGNORE INTO provider_capabilities
  (provider_id, capability, active_protocol, models_dev_id, created_at, updated_at) VALUES
  ('openai',      'llm',    'openai-llm', 'openai',      1, 1),
  ('openai',      'embed',  'openai-embed', NULL,          1, 1),
  ('openai',      'vision', 'openai-llm', 'openai',      1, 1),
  ('openai',      'tts',    'openai-tts', NULL,          1, 1),
  ('openai',      'stt',    'openai-stt', NULL,          1, 1),
  ('anthropic',   'llm',    'anthropic-llm', 'anthropic',   2, 2),
  ('anthropic',   'vision', 'anthropic-llm', 'anthropic',   2, 2),
  ('gemini',      'llm',    'gemini-llm', 'google',      3, 3),
  ('gemini',      'vision', 'gemini-llm', 'google',      3, 3),
  ('deepseek',    'llm',    'openai-llm', 'deepseek',    4, 4),
  ('moonshot',    'llm',    'openai-llm', 'moonshotai',  5, 5),
  ('moonshot',    'vision', 'openai-llm', 'moonshotai',  5, 5),
  ('zhipu',       'llm',    'openai-llm', 'zhipuai',     6, 6),
  ('zhipu',       'embed',  'openai-embed', NULL,          6, 6),
  ('zhipu',       'vision', 'openai-llm', 'zhipuai',     6, 6),
  ('openrouter',  'llm',    'openai-llm', 'openrouter',  7, 7),
  ('openrouter',  'vision', 'openai-llm', 'openrouter',  7, 7),
  ('groq',        'llm',    'openai-llm', 'groq',        8, 8),
  ('groq',        'vision', 'openai-llm', 'groq',        8, 8),
  ('mistral',     'llm',    'openai-llm', 'mistral',     9, 9),
  ('mistral',     'vision', 'openai-llm', 'mistral',     9, 9),
  ('xai',         'llm',    'openai-llm', 'xai',        10, 10),
  ('xai',         'vision', 'openai-llm', 'xai',        10, 10),
  ('perplexity',  'llm',    'openai-llm', 'perplexity', 11, 11),
  ('perplexity',  'vision', 'openai-llm', 'perplexity', 11, 11),
  ('together',    'llm',    'openai-llm', 'togetherai', 12, 12),
  ('together',    'embed',  'openai-embed', NULL,         12, 12),
  ('together',    'vision', 'openai-llm', 'togetherai', 12, 12),
  ('fireworks',   'llm',    'openai-llm', 'fireworks-ai', 13, 13),
  ('fireworks',   'vision', 'openai-llm', 'fireworks-ai', 13, 13),
  ('ollama',      'llm',    'openai-llm', NULL,         14, 14),
  ('ollama',      'embed',  'openai-embed', NULL,         14, 14),
  ('ollama',      'vision', 'openai-llm', NULL,         14, 14),
  ('lmstudio',    'llm',    'openai-llm', NULL,         15, 15),
  ('lmstudio',    'embed',  'openai-embed', NULL,         15, 15),
  ('siliconflow', 'llm',    'openai-llm', 'siliconflow', 16, 16),
  ('siliconflow', 'embed',  'openai-embed', NULL,         16, 16),
  ('siliconflow', 'rerank', 'cohere-rerank', NULL,         16, 16),
  ('siliconflow', 'vision', 'openai-llm', 'siliconflow', 16, 16),
  ('siliconflow', 'tts',    'openai-tts', NULL,         16, 16),
  ('siliconflow', 'stt',    'openai-stt', NULL,         16, 16),
  ('jina',        'embed',  'openai-embed', NULL,         17, 17),
  ('jina',        'rerank', 'cohere-rerank', NULL,         17, 17),
  ('dashscope',   'tts',    'dashscope-tts', NULL,         18, 18),
  ('gpt-sovits',  'tts',    'gpt-sovits-tts', NULL,         19, 19);

INSERT OR IGNORE INTO provider_protocols
  (provider_id, capability, protocol, base_url, created_at, updated_at) VALUES
  ('openai',      'llm',    'openai-llm',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'llm',    'openai-responses-llm', 'https://api.openai.com/v1',                 1, 1),
  ('openai',      'embed',  'openai-embed',         'https://api.openai.com/v1',                 1, 1),
  ('openai',      'vision', 'openai-llm',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'vision', 'openai-responses-llm', 'https://api.openai.com/v1',                 1, 1),
  ('openai',      'tts',    'openai-tts',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'stt',    'openai-stt',           'https://api.openai.com/v1',                 1, 1),
  ('anthropic',   'llm',    'anthropic-llm',        'https://api.anthropic.com/v1',              2, 2),
  ('anthropic',   'vision', 'anthropic-llm',        'https://api.anthropic.com/v1',              2, 2),
  ('gemini',      'llm',    'gemini-llm',           'https://generativelanguage.googleapis.com', 3, 3),
  ('gemini',      'vision', 'gemini-llm',           'https://generativelanguage.googleapis.com', 3, 3),
  ('deepseek',    'llm',    'openai-llm',           'https://api.deepseek.com',                  4, 4),
  ('deepseek',    'llm',    'anthropic-llm',        'https://api.deepseek.com/anthropic',        4, 4),
  ('moonshot',    'llm',    'openai-llm',           'https://api.moonshot.cn/v1',                5, 5),
  ('moonshot',    'vision', 'openai-llm',           'https://api.moonshot.cn/v1',                5, 5),
  ('zhipu',       'llm',    'openai-llm',           'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('zhipu',       'embed',  'openai-embed',         'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('zhipu',       'vision', 'openai-llm',           'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('openrouter',  'llm',    'openai-llm',           'https://openrouter.ai/api/v1',              7, 7),
  ('openrouter',  'vision', 'openai-llm',           'https://openrouter.ai/api/v1',              7, 7),
  ('groq',        'llm',    'openai-llm',           'https://api.groq.com/openai/v1',            8, 8),
  ('groq',        'vision', 'openai-llm',           'https://api.groq.com/openai/v1',            8, 8),
  ('mistral',     'llm',    'openai-llm',           'https://api.mistral.ai/v1',                 9, 9),
  ('mistral',     'vision', 'openai-llm',           'https://api.mistral.ai/v1',                 9, 9),
  ('xai',         'llm',    'openai-llm',           'https://api.x.ai/v1',                      10, 10),
  ('xai',         'vision', 'openai-llm',           'https://api.x.ai/v1',                      10, 10),
  ('perplexity',  'llm',    'openai-llm',           'https://api.perplexity.ai',                11, 11),
  ('perplexity',  'vision', 'openai-llm',           'https://api.perplexity.ai',                11, 11),
  ('together',    'llm',    'openai-llm',           'https://api.together.xyz/v1',              12, 12),
  ('together',    'embed',  'openai-embed',         'https://api.together.xyz/v1',              12, 12),
  ('together',    'vision', 'openai-llm',           'https://api.together.xyz/v1',              12, 12),
  ('fireworks',   'llm',    'openai-llm',           'https://api.fireworks.ai/inference/v1',    13, 13),
  ('fireworks',   'vision', 'openai-llm',           'https://api.fireworks.ai/inference/v1',    13, 13),
  ('ollama',      'llm',    'openai-llm',           'http://localhost:11434/v1',                14, 14),
  ('ollama',      'embed',  'openai-embed',         'http://localhost:11434/v1',                14, 14),
  ('ollama',      'vision', 'openai-llm',           'http://localhost:11434/v1',                14, 14),
  ('lmstudio',    'llm',    'openai-llm',           'http://localhost:1234/v1',                 15, 15),
  ('lmstudio',    'embed',  'openai-embed',         'http://localhost:1234/v1',                 15, 15),
  ('siliconflow', 'llm',    'openai-llm',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'embed',  'openai-embed',         'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'rerank', 'cohere-rerank',        'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'vision', 'openai-llm',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'tts',    'openai-tts',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'stt',    'openai-stt',           'https://api.siliconflow.cn/v1',            16, 16),
  ('jina',        'embed',  'openai-embed',         'https://api.jina.ai/v1',                   17, 17),
  ('jina',        'rerank', 'cohere-rerank',        'https://api.jina.ai/v1',                   17, 17),
  ('dashscope',   'tts',    'dashscope-tts',        'https://dashscope.aliyuncs.com',           18, 18),
  ('gpt-sovits',  'tts',    'gpt-sovits-tts',       'http://127.0.0.1:9880',                    19, 19);

INSERT OR IGNORE INTO provider_models
  (provider_id, capability, model_id, name, source, context_window, max_output, tool_call, reasoning,
   temperature, input_image, embedding_dim, rerank_max_chunks, created_at, updated_at) VALUES
  ('openai',      'embed',  'text-embedding-3-small', 'Text Embedding 3 Small', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 1536, NULL, 0, 0),
  ('openai',      'embed',  'text-embedding-3-large', 'Text Embedding 3 Large', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 3072, NULL, 0, 0),
  ('openai',      'tts',    'gpt-4o-mini-tts',        'GPT-4o Mini TTS', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('openai',      'tts',    'tts-1',                  'TTS-1', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('openai',      'tts',    'tts-1-hd',               'TTS-1 HD', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('openai',      'stt',    'whisper-1',              'Whisper v1', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('openai',      'stt',    'gpt-4o-transcribe',      'GPT-4o Transcribe', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('openai',      'stt',    'gpt-4o-mini-transcribe', 'GPT-4o Mini Transcribe', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('zhipu',       'embed',  'embedding-3',            'Embedding 3', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 2048, NULL, 0, 0),
  ('together',    'embed',  'togethercomputer/m2-bert-80M-8k-retrieval', 'M2-BERT 80M 8K Retrieval', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 768, NULL, 0, 0),
  ('ollama',      'embed',  'nomic-embed-text',       'Nomic Embed Text', 'seed',  NULL, NULL, NULL, NULL, NULL, NULL, 768,  NULL, 0, 0),
  ('ollama',      'embed',  'mxbai-embed-large',      'MxBai Embed Large', 'seed',  NULL, NULL, NULL, NULL, NULL, NULL, 1024, NULL, 0, 0),
  ('ollama',      'vision', 'llava',                  'LLaVA', 'seed', 4096, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('ollama',      'vision', 'llava-llama3',           'LLaVA Llama 3', 'seed', 8192, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('ollama',      'vision', 'moondream',              'Moondream', 'seed', 2048, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('siliconflow', 'embed',  'Pro/BAAI/bge-m3',        'BGE-M3 (Pro)', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 1024, NULL, 0, 0),
  ('siliconflow', 'embed',  'BAAI/bge-large-zh-v1.5', 'BGE Large 中文 v1.5', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 1024, NULL, 0, 0),
  ('siliconflow', 'rerank', 'BAAI/bge-reranker-v2-m3', 'BGE Reranker v2 M3', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('siliconflow', 'tts',    'FunAudioLLM/CosyVoice2-0.5B', 'CosyVoice2 0.5B', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('siliconflow', 'tts',    'fnlp/MOSS-TTSD-v0.5',    'MOSS TTSD v0.5', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('siliconflow', 'stt',    'FunAudioLLM/SenseVoiceSmall', 'SenseVoice Small', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('jina',        'embed',  'jina-embeddings-v3',     'Jina Embeddings v3', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 1024, NULL, 0, 0),
  ('jina',        'embed',  'jina-embeddings-v2-base-zh', 'Jina Embeddings v2 中文 Base', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, 768, NULL, 0, 0),
  ('jina',        'rerank', 'jina-reranker-v2-base-multilingual', 'Jina Reranker v2 多语言 Base', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'cosyvoice-v3-flash',     'CosyVoice v3 Flash', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'cosyvoice-v3-plus',      'CosyVoice v3 Plus', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'cosyvoice-v3.5-flash',   'CosyVoice v3.5 Flash', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'cosyvoice-v3.5-plus',    'CosyVoice v3.5 Plus', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'cosyvoice-v2',           'CosyVoice v2', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'qwen3-tts-flash-realtime', 'Qwen3 TTS Flash Realtime', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'qwen3-tts-instruct-flash-realtime', 'Qwen3 TTS Instruct Flash Realtime', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('dashscope',   'tts',    'qwen-tts-realtime',      'Qwen TTS Realtime', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0),
  ('gpt-sovits',  'tts',    'default',                '默认模型', 'seed', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0);
