-- Provider 种子：19 个内置供应商的能力与协议档。
-- 全部 INSERT OR IGNORE；providers 无启停列，能力可用性 = active_protocol + key。
-- created_at 1..19 即设置页卡片顺序（providers 列表按 created_at ASC 排序）。
-- 演进规则（写进施工单）：后续新增 provider/协议只追加新迁移；
-- 协议演进必须 WHERE EXISTS 对应 providers / provider_capabilities 行，
-- 尊重用户删除；永不 UPDATE/DELETE 用户行。
-- 模型不种子：llm/vision 候选来自 models.dev 内存目录，其余能力手填；
-- provider_models 行 = 用户动过的模型（手填或目录选中落行）。

INSERT OR IGNORE INTO providers (id, name, icon_id, auth_type, created_at, updated_at) VALUES
  ('openai',      'OpenAI',               'openai',      'bearer',  1,  1),
  ('anthropic',   'Anthropic',            'anthropic',   'bearer',  2,  2),
  ('gemini',      'Google Gemini',        'gemini',      'bearer',  3,  3),
  ('deepseek',    'DeepSeek',             'deepseek',    'bearer',  4,  4),
  ('moonshot',    'Moonshot Kimi',        'moonshot',    'bearer',  5,  5),
  ('zhipu',       '智谱 GLM',             'zhipu',       'bearer',  6,  6),
  ('openrouter',  'OpenRouter',           'openrouter',  'bearer',  7,  7),
  ('groq',        'Groq',                 'groq',        'bearer',  8,  8),
  ('mistral',     'Mistral',              'mistral',     'bearer',  9,  9),
  ('xai',         'xAI Grok',             'xai',         'bearer', 10, 10),
  ('perplexity',  'Perplexity',           'perplexity',  'bearer', 11, 11),
  ('together',    'Together AI',          'together',    'bearer', 12, 12),
  ('fireworks',   'Fireworks AI',         'fireworks',   'bearer', 13, 13),
  ('ollama',      'Ollama',               'ollama',      'none',   14, 14),
  ('lmstudio',    'LM Studio',            'lmstudio',    'none',   15, 15),
  ('siliconflow', 'SiliconFlow',          'siliconflow', 'bearer', 16, 16),
  ('jina',        'Jina AI',              'jina',        'bearer', 17, 17),
  ('dashscope',   '阿里云百炼 (DashScope)', 'dashscope', 'bearer',  18, 18),
  ('gpt-sovits',  'GPT-SoVITS (本地)',    'gpt-sovits',  'none',   19, 19);

INSERT OR IGNORE INTO provider_capabilities
  (provider_id, capability, active_protocol, models_dev_id, created_at, updated_at) VALUES
  ('openai',      'llm',    'openai-llm', 'openai',      1, 1),
  ('openai',      'embed',  'openai-embed', NULL,          1, 1),
  ('openai',      'vision', 'openai-llm', 'openai',      1, 1),
  ('openai',      'tts',    'openai-tts', NULL,          1, 1),
  ('openai',      'stt',    'openai-stt', NULL,          1, 1),
  ('anthropic',   'llm',    'anthropic-llm', 'anthropic',   2, 2),
  ('anthropic',   'vision', 'anthropic-llm', 'anthropic',   2, 2),
  ('gemini',      'llm',    'gemini-llm', 'google',      3, 3),
  ('gemini',      'vision', 'gemini-llm', 'google',      3, 3),
  ('deepseek',    'llm',    'openai-llm', 'deepseek',    4, 4),
  ('moonshot',    'llm',    'openai-llm', 'moonshotai',  5, 5),
  ('moonshot',    'vision', 'openai-llm', 'moonshotai',  5, 5),
  ('zhipu',       'llm',    'openai-llm', 'zhipuai',     6, 6),
  ('zhipu',       'embed',  'openai-embed', NULL,          6, 6),
  ('zhipu',       'vision', 'openai-llm', 'zhipuai',     6, 6),
  ('openrouter',  'llm',    'openai-llm', 'openrouter',  7, 7),
  ('openrouter',  'vision', 'openai-llm', 'openrouter',  7, 7),
  ('groq',        'llm',    'openai-llm', 'groq',        8, 8),
  ('groq',        'vision', 'openai-llm', 'groq',        8, 8),
  ('mistral',     'llm',    'openai-llm', 'mistral',     9, 9),
  ('mistral',     'vision', 'openai-llm', 'mistral',     9, 9),
  ('xai',         'llm',    'openai-llm', 'xai',        10, 10),
  ('xai',         'vision', 'openai-llm', 'xai',        10, 10),
  ('perplexity',  'llm',    'openai-llm', 'perplexity', 11, 11),
  ('perplexity',  'vision', 'openai-llm', 'perplexity', 11, 11),
  ('together',    'llm',    'openai-llm', 'togetherai', 12, 12),
  ('together',    'embed',  'openai-embed', NULL,         12, 12),
  ('together',    'vision', 'openai-llm', 'togetherai', 12, 12),
  ('fireworks',   'llm',    'openai-llm', 'fireworks-ai', 13, 13),
  ('fireworks',   'vision', 'openai-llm', 'fireworks-ai', 13, 13),
  ('ollama',      'llm',    'openai-llm', NULL,         14, 14),
  ('ollama',      'embed',  'openai-embed', NULL,         14, 14),
  ('ollama',      'vision', 'openai-llm', NULL,         14, 14),
  ('lmstudio',    'llm',    'openai-llm', NULL,         15, 15),
  ('lmstudio',    'embed',  'openai-embed', NULL,         15, 15),
  ('siliconflow', 'llm',    'openai-llm', 'siliconflow', 16, 16),
  ('siliconflow', 'embed',  'openai-embed', NULL,         16, 16),
  ('siliconflow', 'rerank', 'cohere-rerank', NULL,         16, 16),
  ('siliconflow', 'vision', 'openai-llm', 'siliconflow', 16, 16),
  ('siliconflow', 'tts',    'openai-tts', NULL,         16, 16),
  ('siliconflow', 'stt',    'openai-stt', NULL,         16, 16),
  ('jina',        'embed',  'openai-embed', NULL,         17, 17),
  ('jina',        'rerank', 'cohere-rerank', NULL,         17, 17),
  ('dashscope',   'tts',    'dashscope-tts', NULL,         18, 18),
  ('gpt-sovits',  'tts',    'gpt-sovits-tts', NULL,         19, 19);

INSERT OR IGNORE INTO provider_protocols
  (provider_id, capability, protocol, base_url, created_at, updated_at) VALUES
  ('openai',      'llm',    'openai-llm',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'llm',    'openai-responses-llm', 'https://api.openai.com/v1',                 1, 1),
  ('openai',      'embed',  'openai-embed',         'https://api.openai.com/v1',                 1, 1),
  ('openai',      'vision', 'openai-llm',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'vision', 'openai-responses-llm', 'https://api.openai.com/v1',                 1, 1),
  ('openai',      'tts',    'openai-tts',           'https://api.openai.com/v1',                 1, 1),
  ('openai',      'stt',    'openai-stt',           'https://api.openai.com/v1',                 1, 1),
  ('anthropic',   'llm',    'anthropic-llm',        'https://api.anthropic.com/v1',              2, 2),
  ('anthropic',   'vision', 'anthropic-llm',        'https://api.anthropic.com/v1',              2, 2),
  ('gemini',      'llm',    'gemini-llm',           'https://generativelanguage.googleapis.com', 3, 3),
  ('gemini',      'vision', 'gemini-llm',           'https://generativelanguage.googleapis.com', 3, 3),
  ('deepseek',    'llm',    'openai-llm',           'https://api.deepseek.com',                  4, 4),
  ('deepseek',    'llm',    'anthropic-llm',        'https://api.deepseek.com/anthropic',        4, 4),
  ('moonshot',    'llm',    'openai-llm',           'https://api.moonshot.cn/v1',                5, 5),
  ('moonshot',    'vision', 'openai-llm',           'https://api.moonshot.cn/v1',                5, 5),
  ('zhipu',       'llm',    'openai-llm',           'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('zhipu',       'embed',  'openai-embed',         'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('zhipu',       'vision', 'openai-llm',           'https://open.bigmodel.cn/api/paas/v4',      6, 6),
  ('openrouter',  'llm',    'openai-llm',           'https://openrouter.ai/api/v1',              7, 7),
  ('openrouter',  'vision', 'openai-llm',           'https://openrouter.ai/api/v1',              7, 7),
  ('groq',        'llm',    'openai-llm',           'https://api.groq.com/openai/v1',            8, 8),
  ('groq',        'vision', 'openai-llm',           'https://api.groq.com/openai/v1',            8, 8),
  ('mistral',     'llm',    'openai-llm',           'https://api.mistral.ai/v1',                 9, 9),
  ('mistral',     'vision', 'openai-llm',           'https://api.mistral.ai/v1',                 9, 9),
  ('xai',         'llm',    'openai-llm',           'https://api.x.ai/v1',                      10, 10),
  ('xai',         'vision', 'openai-llm',           'https://api.x.ai/v1',                      10, 10),
  ('perplexity',  'llm',    'openai-llm',           'https://api.perplexity.ai',                11, 11),
  ('perplexity',  'vision', 'openai-llm',           'https://api.perplexity.ai',                11, 11),
  ('together',    'llm',    'openai-llm',           'https://api.together.xyz/v1',              12, 12),
  ('together',    'embed',  'openai-embed',         'https://api.together.xyz/v1',              12, 12),
  ('together',    'vision', 'openai-llm',           'https://api.together.xyz/v1',              12, 12),
  ('fireworks',   'llm',    'openai-llm',           'https://api.fireworks.ai/inference/v1',    13, 13),
  ('fireworks',   'vision', 'openai-llm',           'https://api.fireworks.ai/inference/v1',    13, 13),
  ('ollama',      'llm',    'openai-llm',           'http://localhost:11434/v1',                14, 14),
  ('ollama',      'embed',  'openai-embed',         'http://localhost:11434/v1',                14, 14),
  ('ollama',      'vision', 'openai-llm',           'http://localhost:11434/v1',                14, 14),
  ('lmstudio',    'llm',    'openai-llm',           'http://localhost:1234/v1',                 15, 15),
  ('lmstudio',    'embed',  'openai-embed',         'http://localhost:1234/v1',                 15, 15),
  ('siliconflow', 'llm',    'openai-llm',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'embed',  'openai-embed',         'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'rerank', 'cohere-rerank',        'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'vision', 'openai-llm',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'tts',    'openai-tts',           'https://api.siliconflow.cn/v1',            16, 16),
  ('siliconflow', 'stt',    'openai-stt',           'https://api.siliconflow.cn/v1',            16, 16),
  ('jina',        'embed',  'openai-embed',         'https://api.jina.ai/v1',                   17, 17),
  ('jina',        'rerank', 'cohere-rerank',        'https://api.jina.ai/v1',                   17, 17),
  ('dashscope',   'tts',    'dashscope-tts',        'https://dashscope.aliyuncs.com',           18, 18),
  ('gpt-sovits',  'tts',    'gpt-sovits-tts',       'http://127.0.0.1:9880',                    19, 19);
